import { Button } from '../ui/Button'
import { useI18n } from '../../lib/i18n'
import { tLocale } from '../../lib/i18n/locale'
import { LegalDocBody } from './LegalDocBody'

type PrivacyPolicyProps = {
  onBack: () => void
}

/**
 * Privacy Policy — DRAFT for legal review.
 *
 * ⚠️ IMPORTANT: This text is a draft generated by AI.
 * It MUST be reviewed and approved by a qualified lawyer before
 * being used in production. See LEGAL_TODO.md for details.
 */
export function PrivacyPolicy({ onBack }: PrivacyPolicyProps) {
  const { t, language } = useI18n()
  return (
    <div className="overflow-y-auto touch-pan-y max-h-dvh pb-24 [scrollbar-width:none]">
      <article className="rounded-[32px] border border-white/10 bg-[var(--shop-panel)] p-5 shadow-[0_18px_40px_rgba(0,0,0,0.28)] backdrop-blur-xl">
        {/* Header */}
        <div className="mb-6 flex items-center justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-[0.28em] text-[var(--shop-muted)]">
              {t('legal.kicker')}
            </p>
            <h2 className="mt-1 text-2xl font-bold tracking-[-0.03em] text-[var(--shop-cream)]">
              {t('legal.privacyTitle')}
            </h2>
          </div>
          <span className="rounded-full bg-amber-500/15 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-amber-400">
            {t('legal.draft')}
          </span>
        </div>

        <div className="space-y-5 text-sm leading-6 text-zinc-300">
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">
            {t('legal.lastUpdated', { date: new Date().toLocaleDateString(tLocale(language), { day: 'numeric', month: 'long', year: 'numeric' }) })}
          </p>

          <LegalDocBody doc="privacy" />
        </div>

        {/* Back button */}
        <Button onClick={onBack} variant="primary" size="lg" fullWidth className="mt-6">
          {t('legal.back')}
        </Button>

        {/* Disclaimer */}
        <p className="mt-4 text-center text-[10px] font-semibold uppercase tracking-[0.16em] text-amber-500/70">
          {t('legal.disclaimerPrivacy')}
        </p>
      </article>
    </div>
  )
}
